name = "AdministrativeToolBox Browser"

interpreter = "./vendor/pyodide/pyodide.mjs"

packages = [
  "./vendor/wheels/pypdf-5.9.0-py3-none-any.whl",
  "./vendor/wheels/openpyxl-3.1.5-py2.py3-none-any.whl",
  "./vendor/wheels/et_xmlfile-2.0.0-py3-none-any.whl"
]

[[fetch]]
from = "../"
files = [
  "toolbox/__init__.py",
  "toolbox/siscac_payments.py",
  "toolbox/efdreinf_xml.py"
]
